server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/qianxunclub/spring-boot-config-repo
#          searchPaths: respo
          search-paths: /**
#          username: ldh
#          password: 
      label: master
  application:
    name: config-server
    
      
      