server:
  port: 3001

spring:
  application:
    name: eureka-client

#注册中心指向start    
eureka:
  instance:
    instance-id: eureka-client1
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://admin:a123123@127.0.0.1:1234/eureka/
#注册中心指向end