server:
  port: 8881
  
spring:
  cloud:
    config:
      label: master
      profile: dev
      discovery: 
        enabled: false
        serviceId: config-server
#      uri: http://localhost:8888/
  application:
    name: config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
    
      
      