server:
  port: 3100

spring:
  application:
    name: ribbon-consumer

#注册中心指向start    
eureka:
  instance:
    instance-id: ribbon-consumer
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://admin:a123123@127.0.0.1:1234/eureka/
#注册中心指向end